version: '2'
services:
  stellar:
    build:
      context: ./src/stellar
    image: stellar:latest
    volumes : 
      - "./data:/opt/stellar"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=mypass123
      - PGPASS=mypass123